### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by e8johan** [donaloconnor/automon#2]
What license applies to this project?

**Comment by lukeandrew** [comment]
I've had the same question, and hope that the answer allows commercial use, like LGPL or others, Donal?

**Comment by donaloconnor** [comment]
Hey, I'd love to release it as BSD or something similar but I've noticed I use GPL code: https://github.com/donaloconnor/automon/blob/master/S5WDial.cpp

I'll contact michael.pyne@kdemail.net and see if he's okay re-licensing it as BSD. I don't think I can make it BSD if I include GPL.

**Comment by lukeandrew** [comment]
Good point.  Keep us updated.  If we need to find/replace the dial widgets to change the licensing, please let me know - I'd prefer to spend the time up front to avoid the GPL restraints.

**Comment by donaloconnor** [comment]
I emailed Michael Pyne mpyne@kde.org and he gave me permission to re license his files to the same as stackblur (BSD). 

The license for automon is the BSD 2-clause “Simplified” License.

Thanks.

**Comment by lukeandrew** [comment]
Good work, thanks!  Now to dust off my OBD devices and get to work....
